name: NeboStats
version: ${project.version}
main: xyz.cosmicity.nebostats.NeboStats
api-version: 1.16
authors: [ Nebula_1, CosmicSilence, DistantNeb ]
commands:
  home:
    description: Teleport to a home.
    usage: /home
  homes:
    description: List your homes.
    usage: /homes
  sethome:
    description: Set a home.
    usage: /sethome
  delhome:
    description: Delete a home.
    usage: /delhome [name]